version: "3"
services:
  eventshandler:
    container_name: events-handler
    build:
      context: ..
      dockerfile: docker/dockerfiles/EventsHandlerDockerfile
    env_file: envs/EventsHandler.env
    depends_on:
      broker:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  scheduler:
    container_name: scheduler
    build:
      context: ..
      dockerfile: docker/dockerfiles/SchedulerDockerfile
    env_file: envs/Scheduler.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  noticesender:
    container_name: notice-sender
    build:
      context: ..
      dockerfile: docker/dockerfiles/NoitceSenderDockerfile
    env_file: envs/NoticeSender.env
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy